### ISSUE TITLE
curl has 3 lua deps?

### ISSUE THREAD

**Issue by dynnamitt** [uggedal/docker-alpine#7]
It seems that curl needs a-lot-of-lua:

/ # apk add curl
(1/8) Installing run-parts (4.4-r0)
(2/8) Installing openssl (1.0.1k-r0)
(3/8) Installing lua5.2-libs (5.2.3-r0)
(4/8) Installing lua5.2 (5.2.3-r0)
(5/8) Installing lua5.2-posix (32-r1)
(6/8) Installing ca-certificates (20141019-r0)
(7/8) Installing libssh2 (1.4.3-r0)
(8/8) Installing curl (7.39.0-r0)
Executing busybox-1.22.1-r14.trigger
Executing ca-certificates-20141019-r0.trigger
OK: 8 MiB in 23 packages

Any idea if this is normal/good-practice?

Ubuntu doesn't do this I think...

**Comment by uggedal** [comment]
`ca-certificates` depends on lua: http://git.alpinelinux.org/cgit/aports/tree/main/ca-certificates/APKBUILD
